compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: ./deepspeed/ds_3_config_bf16.json
 zero2_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
mixed_precision: bf16
main_process_ip: null
main_process_port: null
main_training_function: main
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false